set -s escape-time 10
set -g base-index 1
set -g status-left-length 30
set -g status-right '%H:%M'
#set -g status-style 'bg=default,fg=default'
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
